"""empty message

Revision ID: 5040e73871f7
Revises: 468492508ff6
Create Date: 2024-03-30 20:12:39.918658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5040e73871f7'
down_revision = '468492508ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'picture')
    op.drop_column('team_member', 'startDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('startDate', sa.DATETIME(), nullable=True))
    op.add_column('team_member', sa.Column('picture', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
