"""empty message

Revision ID: 674ca0bf2518
Revises: 75016bd06479
Create Date: 2024-03-28 15:13:54.857325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674ca0bf2518'
down_revision = '75016bd06479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
